# SDG 9.2.2 — Manufacturing Employment Analysis (India)

In [1]:
import pandas as pd

In [30]:
raw = pd.read_excel("C:/Users/sanvi/Downloads/data acj/Goal9_2026.xlsx", sheet_name='SDG 9', header=None)
raw.head(10)

,0,1,2,3,4,5,6,7,8,9,...,63,64,65,66,67,68,69,70,71,72
0,9.2.2:Manufacturing employment as a proportion...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,State/UT,2017-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,rural,NaN,NaN,urban,NaN,NaN,rural + urban,NaN,NaN,...,NaN,rural,NaN,NaN,urban,NaN,NaN,rural + urban,NaN,NaN
3,NaN,male,female,person,male,female,person,male,female,person,...,person,male,female,person,male,female,person,male,female,person
4,Andhra Pradesh,5.93,6.06,5.98,16.11,26.3,19.2,9.15,10.7,9.73,...,9.64,6.56,9.09,7.59,15.21,21.18,17.12,9.44,12.15,10.48
5,Arunachal Pradesh,1.44,0.1,1.25,3.75,0,3.31,1.77,0.09,1.53,...,3.12,2.62,6.2,4.17,5.56,8.88,6.65,3.11,6.5,4.53
6,Assam,6.14,5.43,6.06,11.28,13.77,11.68,6.66,6.57,6.65,...,9.27,7.43,8.98,7.99,11.99,17.29,13.44,7.99,9.7,8.59
7,Bihar,9.03,1.3,8.64,11.62,14.69,11.87,9.26,3.2,8.93,...,5.17,6.43,7.81,6.81,9.22,8.7,9.15,6.74,7.85,7.03
8,Chhattisgarh,2.34,2.16,2.27,16.78,13.2,15.81,4.99,3.42,4.4,...,6.66,6.13,3.66,5.03,15.93,11.13,14.54,7.99,4.46,6.5
9,Delhi,14.99,21.25,15.19,26.2,9.93,23.92,25.87,10,23.69,...,16.46,14.57,32.4,16.61,21.61,12.61,20.37,21.41,13.07,20.27

In [7]:
df.shape

(45, 73)

In [8]:
df.head(20)

,0,1,2,3,4,5,6,7,8,9,...,63,64,65,66,67,68,69,70,71,72
0,9.2.2:Manufacturing employment as a proportion...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,State/UT,2017-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,rural,NaN,NaN,urban,NaN,NaN,rural + urban,NaN,NaN,...,NaN,rural,NaN,NaN,urban,NaN,NaN,rural + urban,NaN,NaN
3,NaN,male,female,person,male,female,person,male,female,person,...,person,male,female,person,male,female,person,male,female,person
4,Andhra Pradesh,5.93,6.06,5.98,16.11,26.3,19.2,9.15,10.7,9.73,...,9.64,6.56,9.09,7.59,15.21,21.18,17.12,9.44,12.15,10.48
5,Arunachal Pradesh,1.44,0.1,1.25,3.75,0,3.31,1.77,0.09,1.53,...,3.12,2.62,6.2,4.17,5.56,8.88,6.65,3.11,6.5,4.53
6,Assam,6.14,5.43,6.06,11.28,13.77,11.68,6.66,6.57,6.65,...,9.27,7.43,8.98,7.99,11.99,17.29,13.44,7.99,9.7,8.59
7,Bihar,9.03,1.3,8.64,11.62,14.69,11.87,9.26,3.2,8.93,...,5.17,6.43,7.81,6.81,9.22,8.7,9.15,6.74,7.85,7.03
8,Chhattisgarh,2.34,2.16,2.27,16.78,13.2,15.81,4.99,3.42,4.4,...,6.66,6.13,3.66,5.03,15.93,11.13,14.54,7.99,4.46,6.5
9,Delhi,14.99,21.25,15.19,26.2,9.93,23.92,25.87,10,23.69,...,16.46,14.57,32.4,16.61,21.61,12.61,20.37,21.41,13.07,20.27
10,Goa,23.7,7.77,19.21,17.75,15.34,17.1,20.36,11.9,18.03,...,17.8,22.77,10.63,19.55,15.67,16.7,15.93,18.17,14.51,17.22
11,Gujarat,9.86,6.31,9.11,36.88,36.78,36.86,20.86,16.66,20.04,...,21.64,15.39,8.26,12.57,34.71,33.17,34.3,23.29,15.24,20.48
12,Haryana,11.85,9.54,11.5,34.31,31.1,33.87,19.99,16.68,19.5,...,18.26,15.12,10.95,14.06,25.12,18.99,23.93,19.67,13.92,18.36
13,Himachal Pradesh,6.72,1.59,4.5,26.48,16.8,24.59,8.99,2.19,6.18,...,8.6,7.4,3.66,5.59,25.51,21.53,24.33,9.92,4.86,7.57
14,Jharkhand,5.46,8.71,6.02,22.33,15.85,21.17,8.42,10,8.69,...,9.27,7.12,7.06,7.09,17.55,12.63,16.59,9.14,7.49,8.51
15,Karnataka,7.3,8.42,7.6,18.19,28.1,20.56,11.33,15.07,12.29,...,10.86,8.03,10.8,9.05,14.53,19.29,15.9,10.65,13.5,11.61
16,Kerala,9.18,13.08,10.23,12.05,14.61,12.73,10.42,13.73,11.31,...,9.94,9.23,10.66,9.79,10.65,12.04,11.14,9.9,11.26,10.41
17,Madhya Pradesh,2.98,3.15,3.03,14.59,28.91,17.58,5.65,7.29,6.1,...,7.97,3.3,4.71,3.85,13.56,26.4,16.49,6.15,8,6.8
18,Maharashtra,6.61,2.93,5.4,23.03,18.32,22.03,13.51,7.3,11.74,...,12.66,9.1,5.16,7.58,20.91,18.98,20.42,14.62,9.64,12.97
19,Manipur,6.57,29.07,11.2,8.34,29.53,14.18,7.05,29.23,12.06,...,15.28,7,43.84,22.21,9.43,32.12,19.5,7.64,40.49,21.47

In [16]:
year_row   = raw.iloc[1].ffill()
area_row   = raw.iloc[2].ffill()
gender_row = raw.iloc[3]
data       = raw.iloc[4:42]

rows_out = []
for i, row in data.iterrows():
    state = row[0]
    if pd.isna(state):
        continue
    for col in range(1, len(row)):
        val = row[col]
        if pd.isna(val):
            continue
        rows_out.append({
            'state': state,
            'year': str(year_row[col]),
            'area': area_row[col],
            'gender': gender_row[col],
            'value': val
        })

df = pd.DataFrame(rows_out)
df.to_csv(r"C:\Users\sanvi\Downloads\data acj\sdg9_manufacturing_employment_tidy.csv", index=False)
df.head()

            state     year   area  gender  value
0  Andhra Pradesh  2017-18  rural    male   5.93
1  Andhra Pradesh  2017-18  rural  female   6.06
2  Andhra Pradesh  2017-18  rural  person   5.98
3  Andhra Pradesh  2017-18  urban    male  16.11
4  Andhra Pradesh  2017-18  urban  female   26.3

In [18]:
national[['year', 'value']].reset_index(drop=True)

      year  value
0  2017-18  12.13
1  2018-19  12.07
2  2019-20   11.2
3  2020-21   10.9
4  2021-22   11.6
5  2022-23   11.4
6  2023-24  11.44
7     2025  12.14

In [20]:
national = df[(df['state'] == 'India') & (df['area'] == 'rural + urban') & (df['gender'] == 'person')]
national = national.sort_values('year')
national[['year', 'value']].reset_index(drop=True)

      year  value
0  2017-18  12.13
1  2018-19  12.07
2  2019-20   11.2
3  2020-21   10.9
4  2021-22   11.6
5  2022-23   11.4
6  2023-24  11.44
7     2025  12.14

In [22]:
latest_year = df['year'].unique()[-1]
top_states = (df[(df['year'] == latest_year) & (df['area'] == 'rural + urban') & (df['gender'] == 'person')]
              .sort_values('value', ascending=False)
              .head(10))
top_states[['state', 'value']].reset_index(drop=True)

                  state  value
0  Dadra & Nagar Haveli  62.26
1         A & N Islands  21.91
2               Manipur  21.47
3                Punjab  20.64
4               Gujarat  20.48
5                 Delhi  20.27
6            Puducherry  19.65
7               Haryana  18.36
8            Tamil Nadu  17.69
9           West Bengal  17.29

In [23]:
gender_gap = (df[(df['year'] == latest_year) & (df['area'] == 'rural + urban') & (df['gender'].isin(['male','female'])) & (df['state'] != 'India')]
              .pivot(index='state', columns='gender', values='value'))
gender_gap['gap_female_minus_male'] = gender_gap['female'] - gender_gap['male']
gender_gap.sort_values('gap_female_minus_male', ascending=False).head(10)

gender            female   male gap_female_minus_male
state
Lakshadweep        40.23   4.17                 36.06
Manipur            40.49   7.64                 32.85
A & N Islands      28.13  18.63                   9.5
Telangana          17.89   8.73                  9.16
West Bengal        22.49  14.78                  7.71
Ladakh                 8   0.89                  7.11
Jammu & Kashmir     13.5   8.23                  5.27
Arunachal Pradesh    6.5   3.11                  3.39
Mizoram             7.56   4.71                  2.85
Karnataka           13.5  10.65                  2.85

In [24]:
state_data = df[(df['year'] == latest_year) & (df['area'] == 'rural + urban') & (df['gender'] == 'person') & (df['state'] != 'India')]

highest = state_data.loc[state_data['value'].idxmax()]
lowest = state_data.loc[state_data['value'].idxmin()]

print(f"Highest manufacturing employment share: {highest['state']} at {highest['value']}% ({latest_year})")
print(f"Lowest manufacturing employment share: {lowest['state']} at {lowest['value']}% ({latest_year})")

Highest manufacturing employment share: Dadra & Nagar Haveli at 62.26% (2025)
Lowest manufacturing employment share: Meghalaya at 3.08% (2025)

In [25]:
up_data = df[(df['state'] == 'Uttar Pradesh') & (df['area'] == 'rural + urban') & (df['gender'] == 'person')]
up_data = up_data.sort_values('year')
up_data[['year', 'value']].reset_index(drop=True)

      year  value
0  2017-18  11.38
1  2018-19  10.51
2  2019-20   10.5
3  2020-21    8.6
4  2021-22    8.3
5  2022-23    9.2
6  2023-24   8.45
7     2025   9.84

In [26]:
up_rank = state_data.sort_values('value', ascending=False).reset_index(drop=True)
up_position = up_rank[up_rank['state'] == 'Uttar Pradesh'].index[0] + 1
up_value = up_rank[up_rank['state'] == 'Uttar Pradesh']['value'].values[0]

print(f"Uttar Pradesh ranks #{up_position} out of {len(up_rank)} states/UTs with a manufacturing employment share of {up_value}% in {latest_year}.")

Uttar Pradesh ranks #21 out of 36 states/UTs with a manufacturing employment share of 9.84% in 2025.

In [28]:
union_territories = ['A & N Islands', 'Chandigarh', 'Dadra & Nagar Haveli', 'Daman & Diu',
                      'Delhi', 'Jammu & Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry']

latest_data = df[(df['year'] == latest_year) & (df['area'] == 'rural + urban') & (df['gender'] == 'person') & (df['state'] != 'India')]

states_table = latest_data[~latest_data['state'].isin(union_territories)].sort_values('value', ascending=False)
uts_table = latest_data[latest_data['state'].isin(union_territories)].sort_values('value', ascending=False)

print("STATES — Manufacturing Employment Share")
display(states_table[['state', 'value']].reset_index(drop=True))

print("\nUNION TERRITORIES — Manufacturing Employment Share")
display(uts_table[['state', 'value']].reset_index(drop=True))

STATES — Manufacturing Employment Share

                state  value
0             Manipur  21.47
1              Punjab  20.64
2             Gujarat  20.48
3             Haryana  18.36
4          Tamil Nadu  17.69
5         West Bengal  17.29
6                 Goa  17.22
7         Uttarakhand  14.94
8         Maharashtra  12.97
9           Telangana  12.27
10          Karnataka  11.61
11     Andhra Pradesh  10.48
12             Kerala  10.41
13      Uttar Pradesh   9.84
14          Rajasthan   9.45
15              Assam   8.59
16          Jharkhand   8.51
17             Odisha   7.86
18             Sikkim   7.75
19   Himachal Pradesh   7.57
20              Bihar   7.03
21     Madhya Pradesh    6.8
22       Chhattisgarh    6.5
23            Tripura   6.29
24            Mizoram   5.65
25  Arunachal Pradesh   4.53
26           Nagaland    3.6
27          Meghalaya   3.08

UNION TERRITORIES — Manufacturing Employment Share

                  state  value
0  Dadra & Nagar Haveli  62.26
1         A & N Islands  21.91
2                 Delhi  20.27
3            Puducherry  19.65
4           Lakshadweep  13.19
5       Jammu & Kashmir   10.3
6            Chandigarh   9.85
7                Ladakh   4.05

In [29]:
print(f"\nAverage — States: {states_table['value'].mean():.2f}%")
print(f"Average — UTs: {uts_table['value'].mean():.2f}%")

Average — States: 11.03%
Average — UTs: 20.19%

## Story Pitch

## UT's Surpass Big Indian States in Manufacturing Sector Jobs
### Based on the data analysis of the dataset published by MOSPI, it's clearly visible that Indian Union Territories are surpassing big states like Uttar Pradesh for opportunities in the secondary sector. This shows that a disproportionate share of India's industrial workforce is concentrated in U.T.'s that hold a small fraction of the country's population, while states that are home to millions of unemployed workers lag behind.